### ISSUE TITLE
Dynamically assigning an assoc object issue?

### ISSUE THREAD

**Issue by cbrwizard** [aexmachina/factory-girl#100]
Hey, nice work!

However, I am having an issue here. It might not be related to factory-girl though, but it would be great if you could point me into the right direction.

I have 2 mongoose models: user and message.

```js
// models/user.js
const { mongoose, db } = getMongoose()
const { Schema } = mongoose

const userSchema = new Schema({
  email: {
    type: String,
  },
})

const User = db.model('User', userSchema)
module.exports = User
```

```js
// models/message.js
const { mongoose, db } = getMongoose()
const { Schema } = mongoose
const ObjectId = Schema.Types.ObjectId

const messageSchema = new Schema({
  _user: {
    ref: 'User',
    required: true,
    type: ObjectId,
  },
  text: {
    minlength: 2,
    required: true,
    type: String,
  },
})

const Message = db.model('Message', messageSchema)
module.exports = Message
```

As you can see, a `message` record has a `user` reference. Cool.

Next, I have factories for both:

```js
// factories/user.js
const { factory } = require('factory-girl')
const faker = require('faker')
const User = require('models/user')

factory.define('user', User, {
  email: factory.seq('User.email', n => `${faker.internet.email()}_${n}`),
})

module.exports = factory
```

```js
// factories/message.js
const { factory } = require('factory-girl')
const faker = require('faker')

const Message = require('models/message')
require('test/factories/user')

factory.define('message', Message, {
  _user: factory.assoc('user', '_id'),
  text: () => faker.lorem.paragraph(),
})

module.exports = factory
```

Next, I have a working spec in ava.js for a message model:

```js
// test/models/message.js

import test from 'ava'
import factory from 'test/factories/message'

test('default factory is valid', async (t) => {
  const message = await factory.build('message')

  await message.validate()
  t.pass()
})
// ...
```

It passes, everything is awesome. But the problem is that when I want to have a test where I dynamically assign an assoc object to a message like this:

```js
// test/models/message.js
import factory from 'test/factories/message'
// ...

test('validation succeeds when message has a user', async (t) => {
  const user = await factory.create('user')

  await factory.build('message', { _user: user }) // failing here
  t.pass()
})
```

It fails with this error:
```
TypeError: callback is not a function
    at /Users/cbrwizard/apps/squardak/node_modules/mongoose/lib/statemachine.js:136:14
    at Array.map (native)
    at ctor.map (/Users/cbrwizard/apps/squardak/node_modules/mongoose/lib/statemachine.js:135:29)
    at /Users/cbrwizard/apps/squardak/node_modules/src/utils/asyncPopulate.js:21:33
    at Array.map (native)
    at asyncPopulate (/Users/cbrwizard/apps/squardak/node_modules/src/utils/asyncPopulate.js:10:40)
    at /Users/cbrwizard/apps/squardak/node_modules/src/utils/asyncPopulate.js:19:17
    at Array.map (native)
    at asyncPopulate (/Users/cbrwizard/apps/squardak/node_modules/src/utils/asyncPopulate.js:10:40)
    at /Users/cbrwizard/apps/squardak/node_modules/src/utils/asyncPopulate.js:19:17
    at Array.map (native)
    at asyncPopulate (/Users/cbrwizard/apps/squardak/node_modules/src/utils/asyncPopulate.js:10:40)
    at /Users/cbrwizard/apps/squardak/node_modules/src/utils/asyncPopulate.js:19:17
    at Array.map (native)
    at asyncPopulate (/Users/cbrwizard/apps/squardak/node_modules/src/utils/asyncPopulate.js:10:40)
    at Factory._callee$ (/Users/cbrwizard/apps/squardak/node_modules/src/Factory.js:44:11)
    at tryCatch (/Users/cbrwizard/apps/squardak/node_modules/regenerator-runtime/runtime.js:64:40)
    at Generator.invoke [as _invoke] (/Users/cbrwizard/apps/squardak/node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/cbrwizard/apps/squardak/node_modules/regenerator-runtime/runtime.js:116:21)
    at step (/Users/cbrwizard/apps/squardak/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/cbrwizard/apps/squardak/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

Did I do something wrong here or is it a bug? Thank you!

**Comment by aexmachina** [comment]
I think the problem is not FactoryGirl, but your usage. I'm not familiar with Mongoose, but from your example you're setting the `_user` attribute to `user`, does this work if you do it manually?

**Comment by shvetsovdm** [comment]
@cbrwizard this should work

```javascript
factory.build('message', { _user: user._id })
```

**Comment by cbrwizard** [comment]
@shvetsovdm it worked, thanks!
