### ISSUE TITLE
factory.<method> with enabled adapter doesn't work when destructing <method>

### ISSUE THREAD

**Issue by shvetsovdm** [aexmachina/factory-girl#106]
```
import { factory, MongooseAdapter } from 'factory-girl';
import { Company } from 'model';

const adapter = new MongooseAdapter();
factory.setAdapter(adapter);

factory.define('company', Company, {
  name: factory.sequence('company.name', (n) => `Test Company ${n}`)
});

const { create } = factory;

async function wontwork ()
  await create('company');
});
```

It should be due to `this` which become `undefined` on destructing.

```
TypeError: Cannot read property 'getAdapter' of undefined
      at _callee3$ (node_modules/src/FactoryGirl.js:56:21)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
      at step (node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
      at F (node_modules/core-js/library/modules/_export.js:35:28)
      at node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
      at create (node_modules/factory-girl/index.js:899:22)
      at _callee3$ (test/unit/model/feature-test.js:24:11)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
      at step (node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
      at F (node_modules/core-js/library/modules/_export.js:35:28)
      at Context.<anonymous> (node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
```

Note, the stack trace from actual code, not from the example above.

It is fine to use without destructing. But it will be good enhancement for the package if we can safe some typing with destructing methods from the factory object.

Thanks.

**Comment by aexmachina** [comment]
This is by design, and standard for JavaScript class instances. You could write your own:

```
const factory = new FactoryGirl() // to isolate your changes
const { create } = bindFunctions(factory)
function bindFunctions(obj) {
  Object.getOwnPropertyNames(obj).forEach(prop => {
    if (typeof obj[prop] === 'function') obj[prop] = obj[prop].bind(obj)
  })
  return obj
}
```
