### ISSUE TITLE
"Error: Factory packet already defined" when --watch is armed in Mocha.js

### ISSUE THREAD

**Issue by toszter** [aexmachina/factory-girl#116]
When I run my mocha tests with the `--watch` flag enabled in the options... FactoryGirl.js throws an error declaring that the Factory is already defined.  I don't see documentation indicating that there should be an explicit check for already defined factory ids, nor do I see a method to check if they are defined before I attempt to define them.  

As a result, this error:

```
Error: Factory packet already defined
    at FactoryGirl.define (/node_modules/factory-girl/index.js:817:15)
    at Object.<anonymous> (tests.js:22:9)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at /node_modules/mocha/lib/mocha.js:222:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/node_modules/mocha/lib/mocha.js:219:14)
    at Mocha.run (/node_modules/mocha/lib/mocha.js:487:10)
    at loadAndRun (/node_modules/mocha/bin/_mocha:416:22)
    at rerun (/node_modules/mocha/bin/_mocha:444:5)
    at /node_modules/mocha/bin/_mocha:452:7
    at StatWatcher.<anonymous> (/node_modules/mocha/lib/utils.js:196:9)
    at emitTwo (events.js:125:13)
    at StatWatcher.emit (events.js:213:7)
    at StatWatcher._handle.onchange (fs.js:1452:10)
Error: Factory packet already defined
    at FactoryGirl.define (/node_modules/factory-girl/index.js:817:15)
    at Object.<anonymous> (tests.js:23:11)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at /node_modules/mocha/lib/mocha.js:222:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/node_modules/mocha/lib/mocha.js:219:14)
    at Mocha.run (/node_modules/mocha/lib/mocha.js:487:10)
    at loadAndRun (/node_modules/mocha/bin/_mocha:416:22)
    at rerun (/node_modules/mocha/bin/_mocha:444:5)
    at /node_modules/mocha/bin/_mocha:452:7
    at StatWatcher.<anonymous> (/node_modules/mocha/lib/utils.js:196:9)
    at emitTwo (events.js:125:13)
    at StatWatcher.emit (events.js:213:7)
    at StatWatcher._handle.onchange (fs.js:1452:10)

```

**Comment by toszter** [comment]
As a monkeypatch, I have the definition wrapped in a `try { ... } catch (e) { ... }` for now. There must be a more elegant way to do this.

**Comment by toszter** [comment]
This is easily solved using `factory.getFactory("<factory_model_id>", false)`
