### ISSUE TITLE
4.0.0-beta.1 broken?

### ISSUE THREAD

**Issue by kldavis4** [aexmachina/factory-girl#64]
Is 4.0.0-beta.1 broken? If I `npm install factory-girl` I see no lib or index.js in the module directory and I get `Cannot find module 'factory-girl'` error when I try to import it.

**Comment by chetanism** [comment]
Hi @kldavis4, thanks for trying (to try) out the new version :). 
Sorry for the trouble, but you have pointed out right, by mistake we have put the wrong directory on npm. The new version has been completely re-written using es6/es7 and we just needed to publish the directory with transpiled source code, but the whole source directory got published to npm.

@aexmachina has been busy with another assignment, by the time he can get to publish the correct directory, you should be able to continue with importing factory-girl from `factory-girl/dist`.

**Comment by kldavis4** [comment]
Ok @chetanism , thanks for the workaround

**Comment by gunar** [comment]
Could we have a published version that is sync'ed with the latest developments of node?
For example, `node` has generators since v6. Could we get a version that has `import x from x` transpiled, but not generators? Transpiling generators weakens debugging. The stack trace becomes unreadable.

Thank you!

**Comment by gunar** [comment]
Oh, it seems what you're actually doing is transpiling async/await functions into generators.
Still, the stack trace looks horrible :sob:
```
      at node_modules/mongoose/lib/statemachine.js:136:14
      at Array.map (native)
      at StateMachine.map (node_modules/mongoose/lib/statemachine.js:135:29)
      at node_modules/factory-girl/index.js:43:46
      at Array.map (native)
      at asyncPopulate (node_modules/factory-girl/index.js:32:39)
      at node_modules/factory-girl/index.js:41:17
      at Array.map (native)
      at asyncPopulate (node_modules/factory-girl/index.js:32:39)
      at node_modules/factory-girl/index.js:41:17
      at Array.map (native)
      at asyncPopulate (node_modules/factory-girl/index.js:32:39)
      at node_modules/factory-girl/index.js:41:17
      at Array.map (native)
      at asyncPopulate (node_modules/factory-girl/index.js:32:39)
      at Factory._callee$ (node_modules/factory-girl/index.js:118:24)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/regenerator-runtime/runt
ime.js:336:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules/reg
enerator-runtime/runtime.js:95:21)
      at step (node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at node_modules/babel-runtime/helpers/asyncToGenerator.js:28:20
      at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by aexmachina** [comment]
Yep, I agree. I'm trying to get a native build working for Node.js, and will create an issue to create builds for environments that provide async/await.
