### ISSUE TITLE
Mongoose adapter is unable to handle dates

### ISSUE THREAD

**Issue by aturkewi** [aexmachina/factory-girl#95]
When I try create an object from a factory that has a date field, and error returns about casting.

Here is the simplest runnable case:
```js
const mongoose = require('mongoose')
const factory = require('factory-girl').factory;
const factoryGirl = require('factory-girl')

// connect to mongo server with mongoose
mongoose.connect("localhost:27017/qbot_db_development")
mongoose.Promise = Promise

// setup factory with mongoose adapter
const adapter = new factoryGirl.MongooseAdapter();
factory.setAdapter(adapter);

// create some mongoose model
const shiftSchema = new mongoose.Schema({
  started_at: Date,
})
const Shift = mongoose.model('Shift', shiftSchema);

// define the factory witha  default time
factory.define('Shift', Shift, {
  started_at: new Date,
});

factory.create('Shift')
  .then((createdShift) => console.log(createdShift))
  .catch((err) => console.log(err))
```

I saved this in a file and when I run it, I get the following error:
```
// ♥ node scratch-pad.js 
{ ValidationError: Shift validation failed
    at MongooseError.ValidationError (/Users/avidor/Development/code/instructor/projects/qbot/node_modules/mongoose/lib/error/validation.js:23:11)
    at model.Document.invalidate (/Users/avidor/Development/code/instructor/projects/qbot/node_modules/mongoose/lib/document.js:1535:32)
    at model.Document.set (/Users/avidor/Development/code/instructor/projects/qbot/node_modules/mongoose/lib/document.js:777:10)
    at model._handleIndex (/Users/avidor/Development/code/instructor/projects/qbot/node_modules/mongoose/lib/document.js:623:14)
    at model.Document.set (/Users/avidor/Development/code/instructor/projects/qbot/node_modules/mongoose/lib/document.js:583:24)
    at model.Document (/Users/avidor/Development/code/instructor/projects/qbot/node_modules/mongoose/lib/document.js:71:12)
    at model.Model (/Users/avidor/Development/code/instructor/projects/qbot/node_modules/mongoose/lib/model.js:51:12)
    at new model (/Users/avidor/Development/code/instructor/projects/qbot/node_modules/mongoose/lib/model.js:3571:13)
    at MongooseAdapter.build (/Users/avidor/Development/code/instructor/projects/qbot/node_modules/factory-girl/index.js:703:14)
    at Factory._callee2$ (/Users/avidor/Development/code/instructor/projects/qbot/node_modules/factory-girl/index.js:155:33)
    at tryCatch (/Users/avidor/Development/code/instructor/projects/qbot/node_modules/regenerator-runtime/runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/avidor/Development/code/instructor/projects/qbot/node_modules/regenerator-runtime/runtime.js:299:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/avidor/Development/code/instructor/projects/qbot/node_modules/regenerator-runtime/runtime.js:116:21)
    at step (/Users/avidor/Development/code/instructor/projects/qbot/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/avidor/Development/code/instructor/projects/qbot/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at process._tickCallback (internal/process/next_tick.js:103:7)
  errors: 
   { started_at: 
      { CastError: Cast to Date failed for value "{}" at path "started_at"
          at MongooseError.CastError (/Users/avidor/Development/code/instructor/projects/qbot/node_modules/mongoose/lib/error/cast.js:26:11)
          at model.Document.set (/Users/avidor/Development/code/instructor/projects/qbot/node_modules/mongoose/lib/document.js:778:7)
          at model._handleIndex (/Users/avidor/Development/code/instructor/projects/qbot/node_modules/mongoose/lib/document.js:623:14)
          at model.Document.set (/Users/avidor/Development/code/instructor/projects/qbot/node_modules/mongoose/lib/document.js:583:24)
          at model.Document (/Users/avidor/Development/code/instructor/projects/qbot/node_modules/mongoose/lib/document.js:71:12)
          at model.Model (/Users/avidor/Development/code/instructor/projects/qbot/node_modules/mongoose/lib/model.js:51:12)
          at new model (/Users/avidor/Development/code/instructor/projects/qbot/node_modules/mongoose/lib/model.js:3571:13)
          at MongooseAdapter.build (/Users/avidor/Development/code/instructor/projects/qbot/node_modules/factory-girl/index.js:703:14)
          at Factory._callee2$ (/Users/avidor/Development/code/instructor/projects/qbot/node_modules/factory-girl/index.js:155:33)
          at tryCatch (/Users/avidor/Development/code/instructor/projects/qbot/node_modules/regenerator-runtime/runtime.js:64:40)
          at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/avidor/Development/code/instructor/projects/qbot/node_modules/regenerator-runtime/runtime.js:299:22)
          at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/avidor/Development/code/instructor/projects/qbot/node_modules/regenerator-runtime/runtime.js:116:21)
          at step (/Users/avidor/Development/code/instructor/projects/qbot/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
          at /Users/avidor/Development/code/instructor/projects/qbot/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
          at process._tickCallback (internal/process/next_tick.js:103:7)
          at Module.runMain (module.js:606:11)
        message: 'Cast to Date failed for value "{}" at path "started_at"',
        name: 'CastError',
        stringValue: '"{}"',
        kind: 'Date',
        value: {},
        path: 'started_at',
        reason: [Object] } },
  message: 'Shift validation failed',
  name: 'ValidationError' }
```

It looks like my date is getting converted into an empty object somehow.

**Comment by aturkewi** [comment]
@lukeghenco feel free to add any notes/thoughts if you have :)

**Comment by aturkewi** [comment]
As I keep working on this, I found that dates _can_ be used if they're treated as a string:

```js
factory.define('Shift', Shift, {
  started_at: `${new Date}`,
});
```

This doesn't feel like a great solution as much as a workaround... If you feel this is an adequate solution though, it should probably be added to the docs?

**Comment by aexmachina** [comment]
You just need to provide a function that returns a Date:

```js
factory.define('Shift', Shift, {
  started_at: () => new Date,
});
```

**Comment by villins** [comment]
@aexmachina I met the same problem when I run factory.create('Order', {paidAt: new Date()}) with pass date params

**Comment by aexmachina** [comment]
See comment here https://github.com/aexmachina/factory-girl/issues/111#issuecomment-328774985
